### ISSUE TITLE
Programming Track Power

### ISSUE THREAD

**Issue by kwledbetter** [DCC-EX/BaseStation-Classic#2]
Currently the DCC++ code powers both tracks on power on.  Programming track should only be powered when programming and then off.

I think an easy fix by taking the program power off by default and powering on in the read and write loops and once complete powering back off

**Comment by davidcutting42** [comment]
@FrightRisk can we close this as a "wont-fix"?

**Comment by ianmidd** [comment]
I have a similar problem. Installed JMRI on pi4 and DCC++ on Uno  with Arduino Motor shield. Seems to work intermittently. I have 15vdc at the Input terminals. I get 14.9v (AC) on the Output B (programming track) with LEDs. No lights or power to Output A. I'm sure it was working yesterday. What have I done wrong? Did I short something? It "Indentifies" the loco on the Programming track but it will not run with a Throttle. I even tried switching the wires to Output A. But since the LEDs are not on I wasn't expecting much. I have even swapped to another Uno just in case. Any Ideas?

**Comment by FrightRisk** [comment]
DCC++ Classic works the way Gregg originally wrote it, both track turns on by default. If you are not getting power to main, I would normally say there is a short on MAIN, but Classic turns off power to both tracks and the power stays off until you reset the Arduino. So likely, there is a faulty pin connection from pin 3 on the Uno to the Motor Shield, a bad motor shield, or something wrong with the motor board setup in the config.h file (MOTOR_SHIELD_TYPE should be 0), or the pins in DCCpp.h were changed. 

You can measure pin 3 for 5V DC. Send <0> from the serial monitor and pin 3 and 11 should be 0V DC. Send a <1> and both should be 5V DC. If power never comes on to pin 3, then it is a bent pin on the motor shield, bad pin 3 on the Uno, or the sketch is not set to turn on pin 3. If you don't get 5V on pin 5 on the motor shield, take the shield off and check directly on the Uno to see if it is just the connection to the motor shield or the Uno itself.

DCC++EX has much better diagnostics and operates completely differently. It will run on an Uno without WiFi or Ethernet and without EX-RAIL, but we really recommend a Mega ($15 from AliExpress or Banggood). By default, DCC++EX has power OFF to both outputs for safety. You must turn power on in JMRI or Engine Driver or one of the other throttles. This behavior can be changed in a mySetup.h file. The programming track by default comes on and off automatically when you put a loco on the programming track and issue a programming command. If you were doing page reads or writes it would be faster to turn the power on and leave it on for programming instead of it going on and off every time. We have a lot of diagnostics in EX to see what is happening by looking at the serial monitor. And when there is a short, EX automatically tries to turn the power back on and you see the log fill with overlimit messages.

**Comment by ianmidd** [comment]
Thanks for all this. 

Changed over to EX with a Mega. All is well now. Thanks again. 

Regards,

Ian
Sent from my iPhone 
+44 7768 215798
